
post:
    path: /
    controller: App\Controller\PostController::index

form_create:
    path: /post/new
    controller: App\Controller\PostController::showForm

post_delete_all:
  path : /post/delete
  controller: App\Controller\PostController::deleteAllPost

post_show:
    path: /post/{id}
    controller: App\Controller\PostController::showPost

post_delete:
  path : /post/delete/{id}
  controller: App\Controller\PostController::deletePost
