
index:
    path: /
    controller: App\Controller\PostController::index

login:
    path : /login

logout:
    path: /logout
    
register:
    path : /register

post_create:
    path: /post/new
    controller: App\Controller\PostController::createPost

post_delete_all:
    path : /post/delete
    controller: App\Controller\PostController::deleteAllPost

post_show:
    path: /post/{slug}
    controller: App\Controller\PostController::showPost

post_delete:
    path : /post/delete/{id}
    controller: App\Controller\PostController::deletePost

post_edit:
    path : /post/edit/{id}
    controller: App\Controller\PostController::editPost

post_pinned:
    path : /post/pin/{id}
    controller: App\Controller\PostController::pinPost
