
index:
    path: /
    controller: App\Controller\PostController::index

form_create:
    path: /post/new
    controller: App\Controller\PostController::showForm

post_create:
    path: /
    controller: App\Controller\PostController::createPost

post_delete_all:
    path : /post/delete
    controller: App\Controller\PostController::deleteAllPost

post_show:
    path: /post/{id}
    controller: App\Controller\PostController::showPost

post_delete:
    path : /post/delete/{id}
    controller: App\Controller\PostController::deletePost

register:
    path : /register
    controller: App\Controller\RegistrationController::register
