
default:
    path: /
    controller: App\Controller\PostController::homepage

login:
    path : /login

logout:
    path: /logout

register:
    path : /register
handleSearch:
    path : /search
    controller: App\Controller\PostController::handleSearch

index:
    path: /{username}
    controller: App\Controller\PostController::index

post_create:
    path: /post/new
    controller: App\Controller\PostController::createPost

post_show:
    path: /post/{slug}
    controller: App\Controller\PostController::showPost

post_delete:
    path : /post/delete/{id}
    controller: App\Controller\PostController::deletePost

post_edit:
    path : /post/edit/{id}
    controller: App\Controller\PostController::editPost

post_pinned:
    path : /post/pin/{id}
    controller: App\Controller\PostController::pinPost

remark_delete:
    path : /remark/delete/{id}
    controller: App\Controller\RemarkController::deleteRemark

remark_edit:
    path : /remark/edit/{id}
    controller: App\Controller\RemarkController::editRemark
